### ISSUE TITLE
npm install is failing

### ISSUE THREAD

**Issue by cmoulliard** [snowdrop/snowdrop-automation-client#31]
## Issue

npm install is failing

```
npm install
events.js:183░░░░░░⸩ ⠏ extract:xml2json: sill extract apollo-link@1.2.2
      throw er; // Unhandled 'error' event
      ^

Error: write after end
    at writeAfterEnd (_stream_writable.js:236:12)
    at PassThrough.Writable.write (_stream_writable.js:287:5)
    at PassThrough.Writable.end (_stream_writable.js:563:10)
    at ReadEntry.entry.on (/Users/dabou/.nvm/versions/node/v8.11.1/lib/node_modules/npm/node_modules/pacote/lib/extract-stream.js:19:41)
    at emitOne (events.js:121:20)
    at ReadEntry.emit (events.js:211:7)
    at ReadEntry.emit (/Users/dabou/.nvm/versions/node/v8.11.1/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:296:25)
    at ReadEntry.[maybeEmitEnd] (/Users/dabou/.nvm/versions/node/v8.11.1/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:249:12)
    at ReadEntry.end (/Users/dabou/.nvm/versions/node/v8.11.1/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:162:27)
    at Unpack.[consumeBody] (/Users/dabou/.nvm/versions/node/v8.11.1/lib/node_modules/npm/node_modules/tar/lib/parse.js:210:13)
    at Unpack.[consumeChunkSub] (/Users/dabou/.nvm/versions/node/v8.11.1/lib/node_modules/npm/node_modules/tar/lib/parse.js:391:40)
    at Unpack.[consumeChunk] (/Users/dabou/.nvm/versions/node/v8.11.1/lib/node_modules/npm/node_modules/tar/lib/parse.js:360:30)
    at Unzip.(anonymous function).on.chunk (/Users/dabou/.nvm/versions/node/v8.11.1/lib/node_modules/npm/node_modules/tar/lib/parse.js:291:59)
    at emitOne (events.js:116:13)
    at Unzip.emit (events.js:211:7)
    at Unzip.emit (/Users/dabou/.nvm/versions/node/v8.11.1/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:296:25)
events.js:183░░░░░░⸩ ⠙ extract:npm-run-all: sill extract graphql-codegen-compiler@0.13.0
      throw er; // Unhandled 'error' event
      ^

Error: write after end
    at writeAfterEnd (_stream_writable.js:236:12)
    at PassThrough.Writable.write (_stream_writable.js:287:5)
    at PassThrough.Writable.end (_stream_writable.js:563:10)
    at ReadEntry.entry.on (/Users/dabou/.nvm/versions/node/v8.11.1/lib/node_modules/npm/node_modules/pacote/lib/extract-stream.js:19:41)
    at emitOne (events.js:121:20)
    at ReadEntry.emit (events.js:211:7)
    at ReadEntry.emit (/Users/dabou/.nvm/versions/node/v8.11.1/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:296:25)
    at ReadEntry.[maybeEmitEnd] (/Users/dabou/.nvm/versions/node/v8.11.1/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:249:12)
    at ReadEntry.end (/Users/dabou/.nvm/versions/node/v8.11.1/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:162:27)
    at Unpack.[consumeBody] (/Users/dabou/.nvm/versions/node/v8.11.1/lib/node_modules/npm/node_modules/tar/lib/parse.js:210:13)
    at Unpack.[consumeChunkSub] (/Users/dabou/.nvm/versions/node/v8.11.1/lib/node_modules/npm/node_modules/tar/lib/parse.js:391:40)
    at Unpack.[consumeChunk] (/Users/dabou/.nvm/versions/node/v8.11.1/lib/node_modules/npm/node_modules/tar/lib/parse.js:362:30)
    at Unzip.(anonymous function).on.chunk (/Users/dabou/.nvm/versions/node/v8.11.1/lib/node_modules/npm/node_modules/tar/lib/parse.js:291:59)
    at emitOne (events.js:116:13)
    at Unzip.emit (events.js:211:7)
    at Unzip.emit (/Users/dabou/.nvm/versions/node/v8.11.1/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:296:25)
WARN tar ENOENT: no such file or directory, open '/Users/dabou/Code/snowdrop/automation-client/node_modules/.staging/chai-3d40b278/index.js'
WARN tar ENOENT: no such file or directory, open '/Users/dabou/Code/snowdrop/automation-client/node_modules/.staging/chai-3d40b278/karma.conf.js'
WARN tar ENOENT: no such file or directory, open '/Users/dabou/Code/snowdrop/automation-client/node_modules/.staging/chai-3d40b278/register-assert.js'
WARN tar ENOENT: no such file or directory, open '/Users/dabou/Code/snowdrop/automation-client/node_modules/.staging/chai-3d40b278/register-expect.js'
WARN tar ENOENT: no such file or directory, open '/Users/dabou/Code/snowdrop/automation-client/node_modules/.staging/chai-3d40b278/register-should.js'
WARN tar ENOENT: no such file or directory, open '/Users/dabou/Code/snowdrop/automation-client/node_modules/.staging/chai-3d40b278/sauce.browsers.js'
WARN tar ENOENT: no such file or directory, open '/Users/dabou/Code/snowdrop/automation-client/node_modules/.staging/chai-3d40b278/karma.sauce.js'
WARN tar ENOENT: no such file or directory, open '/Users/dabou/Code/snowdrop/automation-client/node_modules/.staging/chai-3d40b278/ReleaseNotes.md'
WARN tar ENOENT: no such file or directory, open '/Users/dabou/Code/snowdrop/automation-client/node_modules/.staging/@types/mocha-7e585808/package.json'
WARN tar ENOENT: no such file or directory, open '/Users/dabou/Code/snowdrop/automation-client/node_modules/.staging/@types/chai-857634d5/package.json'
WARN tar ENOENT: no such file or directory, open '/Users/dabou/Code/snowdrop/automation-client/node_modules/.staging/@types/node-42816d92/module.d.ts'
WARN tar ENOENT: no such file or directory, open '/Users/dabou/Code/snowdrop/automation-client/node_modules/.staging/@types/node-42816d92/net.d.ts'
WARN tar ENOENT: no such file or directory, open '/Users/dabou/Code/snowdrop/automation-client/node_modules/.staging/graphql-tools-896594ec/LICENSE'
WARN tar ENOENT: no such file or directory, open '/Users/dabou/Code/snowdrop/automation-client/node_modules/.staging/graphql-tools-896594ec/README.md'
WARN tar ENOENT: no such file or directory, open '/Users/dabou/Code/snowdrop/automation-client/node_modules/.staging/apollo-link-0335778c/lib/bundle.umd.js.map'
WARN tar ENOENT: no such file or directory, open '/Users/dabou/Code/snowdrop/automation-client/node_modules/.staging/@types/node-6ed8c411/module.d.ts'
WARN tar ENOENT: no such file or directory, open '/Users/dabou/Code/snowdrop/automation-client/node_modules/.staging/@types/node-6ed8c411/net.d.ts'
WARN tar ENOENT: no such file or directory, open '/Users/dabou/Code/snowdrop/automation-client/node_modules/.staging/typescript-207acadc/lib/tsserverlibrary.d.ts'
npm ERR! cancel after 1 retries!
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: write after end
    at writeAfterEnd (_stream_writable.js:236:12)
    at PassThrough.Writable.write (_stream_writable.js:287:5)
    at PassThrough.Writable.end (_stream_writable.js:563:10)
    at ReadEntry.entry.on (/Users/dabou/.nvm/versions/node/v8.11.1/lib/node_modules/npm/node_modules/pacote/lib/extract-stream.js:19:41)
    at emitOne (events.js:121:20)
    at ReadEntry.emit (events.js:211:7)
    at ReadEntry.emit (/Users/dabou/.nvm/versions/node/v8.11.1/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:296:25)
    at ReadEntry.[maybeEmitEnd] (/Users/dabou/.nvm/versions/node/v8.11.1/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:249:12)
    at ReadEntry.end (/Users/dabou/.nvm/versions/node/v8.11.1/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:162:27)
    at Unpack.[consumeBody] (/Users/dabou/.nvm/versions/node/v8.11.1/lib/node_modules/npm/node_modules/tar/lib/parse.js:210:13)
    at Unpack.[consumeChunkSub] (/Users/dabou/.nvm/versions/node/v8.11.1/lib/node_modules/npm/node_modules/tar/lib/parse.js:391:40)
    at Unpack.[consumeChunk] (/Users/dabou/.nvm/versions/node/v8.11.1/lib/node_modules/npm/node_modules/tar/lib/parse.js:362:30)
    at Unzip.(anonymous function).on.chunk (/Users/dabou/.nvm/versions/node/v8.11.1/lib/node_modules/npm/node_modules/tar/lib/parse.js:291:59)
    at emitOne (events.js:116:13)
    at Unzip.emit (events.js:211:7)
    at Unzip.emit (/Users/dabou/.nvm/versions/node/v8.11.1/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:296:25)
```

**Comment by cmoulliard** [comment]
Resolved after moving to node v10 -> `nvm use v10.10.0`
