### ISSUE TITLE
Generating GraphQL types failed: Could not find field type. Commit.impact

### ISSUE THREAD

**Issue by cmoulliard** [snowdrop/snowdrop-automation-client#32]
## Issue

```
npm run clean && npm run compile

> @snowdrop/snowdrop-automation-client@0.1.0 clean /Users/dabou/Code/snowdrop/automation-client
> run-p clean:compile clean:doc clean:run


> @snowdrop/snowdrop-automation-client@0.1.0 clean:doc /Users/dabou/Code/snowdrop/automation-client
> rimraf doc


> @snowdrop/snowdrop-automation-client@0.1.0 clean:compile /Users/dabou/Code/snowdrop/automation-client
> rimraf git-info.json "index.{d.ts,js{,.map}}" "{lib,test}/**/*.{d.ts,js{,.map}}" lib/typings/types.ts


> @snowdrop/snowdrop-automation-client@0.1.0 clean:run /Users/dabou/Code/snowdrop/automation-client
> rimraf *-v8.log profile.txt log


> @snowdrop/snowdrop-automation-client@0.1.0 compile /Users/dabou/Code/snowdrop/automation-client
> run-s git:info gql:gen compile:ts


> @snowdrop/snowdrop-automation-client@0.1.0 git:info /Users/dabou/Code/snowdrop/automation-client
> atm-git-info

Successfully wrote git information to '/Users/dabou/Code/snowdrop/automation-client/git-info.json'

> @snowdrop/snowdrop-automation-client@0.1.0 gql:gen /Users/dabou/Code/snowdrop/automation-client
> atm-gql-gen

Generating GraphQL types failed: Could not find field type. Commit.impact
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @snowdrop/snowdrop-automation-client@0.1.0 gql:gen: `atm-gql-gen`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @snowdrop/snowdrop-automation-client@0.1.0 gql:gen script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/dabou/.npm/_logs/2019-11-20T15_27_20_617Z-debug.log
ERROR: "gql:gen" exited with 1.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @snowdrop/snowdrop-automation-client@0.1.0 compile: `run-s git:info gql:gen compile:ts`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @snowdrop/snowdrop-automation-client@0.1.0 compile script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/dabou/.npm/_logs/2019-11-20T15_27_20_654Z-debug.log
 ✘  ~/Code/snowdrop/automation-client   master ●  >....
> run-s git:info gql:gen compile:ts


> @snowdrop/snowdrop-automation-client@0.1.0 git:info /Users/dabou/Code/snowdrop/automation-client
> atm-git-info

Successfully wrote git information to '/Users/dabou/Code/snowdrop/automation-client/git-info.json'

> @snowdrop/snowdrop-automation-client@0.1.0 gql:gen /Users/dabou/Code/snowdrop/automation-client
> atm-gql-gen

Generating GraphQL types failed: Could not find field type. Commit.impact
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @snowdrop/snowdrop-automation-client@0.1.0 gql:gen: `atm-gql-gen`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @snowdrop/snowdrop-automation-client@0.1.0 gql:gen script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/dabou/.npm/_logs/2019-11-20T15_27_20_617Z-debug.log
ERROR: "gql:gen" exited with 1.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @snowdrop/snowdrop-automation-client@0.1.0 compile: `run-s git:info gql:gen compile:ts`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @snowdrop/snowdrop-automation-client@0.1.0 compile script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/dabou/.npm/_logs/2019-11-20T15_27_20_654Z-debug.log
```

**Comment by cmoulliard** [comment]
Log report

```
cat /Users/dabou/.npm/_logs/2019-11-20T15_27_20_654Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/Users/dabou/.nvm/versions/node/v10.10.0/bin/node',
1 verbose cli   '/Users/dabou/.nvm/versions/node/v10.10.0/bin/npm',
1 verbose cli   'run',
1 verbose cli   'compile' ]
2 info using npm@6.4.1
3 info using node@v10.10.0
4 verbose run-script [ 'precompile', 'compile', 'postcompile' ]
5 info lifecycle @snowdrop/snowdrop-automation-client@0.1.0~precompile: @snowdrop/snowdrop-automation-client@0.1.0
6 info lifecycle @snowdrop/snowdrop-automation-client@0.1.0~compile: @snowdrop/snowdrop-automation-client@0.1.0
7 verbose lifecycle @snowdrop/snowdrop-automation-client@0.1.0~compile: unsafe-perm in lifecycle true
8 verbose lifecycle @snowdrop/snowdrop-automation-client@0.1.0~compile: PATH: /Users/dabou/.nvm/versions/node/v10.10.0/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/dabou/Code/snowdrop/automation-client/node_modules/.bin:/Users/dabou/.nvm/versions/node/v10.10.0/bin:/Users/dabou/MyApplications/gcloud-sdk/bin:/usr/local/opt/postgresql@9.6/bin:/usr/local/sbin:/usr/local/Cellar/pyenv-virtualenv/1.1.1/shims:/usr/local/opt/openssl/bin:/usr/local/opt/curl/bin:/Users/dabou/.jenv/shims:/Users/dabou/.oh-my-zsh/custom/plugins/git-open:/Users/dabou/.rbenv/shims:/Users/dabou/MyApplications/groovy-2.4.9/bin:/Users/dabou/MyApplications/graalvm-ce-19.2.0.1/Contents/Home/bin:/Users/dabou/Library/Python/3.7/bin:/Users/dabou/MyProjects/tech-knowledge/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/kubebuilder/bin:/usr/local/opt/go/libexec/bin:/Users/dabou/Code/go-workspace/bin:/Users/dabou/MyApplications/ibmtools
9 verbose lifecycle @snowdrop/snowdrop-automation-client@0.1.0~compile: CWD: /Users/dabou/Code/snowdrop/automation-client
10 silly lifecycle @snowdrop/snowdrop-automation-client@0.1.0~compile: Args: [ '-c', 'run-s git:info gql:gen compile:ts' ]
11 silly lifecycle @snowdrop/snowdrop-automation-client@0.1.0~compile: Returned: code: 1  signal: null
12 info lifecycle @snowdrop/snowdrop-automation-client@0.1.0~compile: Failed to exec compile script
13 verbose stack Error: @snowdrop/snowdrop-automation-client@0.1.0 compile: `run-s git:info gql:gen compile:ts`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/Users/dabou/.nvm/versions/node/v10.10.0/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:182:13)
13 verbose stack     at ChildProcess.<anonymous> (/Users/dabou/.nvm/versions/node/v10.10.0/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:182:13)
13 verbose stack     at maybeClose (internal/child_process.js:962:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
14 verbose pkgid @snowdrop/snowdrop-automation-client@0.1.0
15 verbose cwd /Users/dabou/Code/snowdrop/automation-client
16 verbose Darwin 19.0.0
17 verbose argv "/Users/dabou/.nvm/versions/node/v10.10.0/bin/node" "/Users/dabou/.nvm/versions/node/v10.10.0/bin/npm" "run" "compile"
18 verbose node v10.10.0
19 verbose npm  v6.4.1
20 error code ELIFECYCLE
21 error errno 1
22 error @snowdrop/snowdrop-automation-client@0.1.0 compile: `run-s git:info gql:gen compile:ts`
22 error Exit status 1
23 error Failed at the @snowdrop/snowdrop-automation-client@0.1.0 compile script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by geoand** [comment]
Again I have no idea what can be causing this.

It works fine locally and it seems to be working on CI as well: https://circleci.com/gh/snowdrop/snowdrop-automation-client/167

**Comment by geoand** [comment]
I sugges trying with the latest version of node `8.x` (I am using `v8.15.1`) instead of `10.x`

**Comment by cmoulliard** [comment]
Will do a test using `nvm install v8.15.1`

**Comment by geoand** [comment]
Thanks

**Comment by cmoulliard** [comment]
Same error using node v8.15.1

```
npm ERR! @snowdrop/snowdrop-automation-client@0.1.0 gql:gen: `atm-gql-gen`
```

**Comment by geoand** [comment]
OK.

@gytis @metacosm do you remember running into this? It doesn't ring a bell for me

**Comment by geoand** [comment]
@iocanel do you have atomist installed locally? If not, can you give it a shot and see if you hit the same issue that @cmoulliard is seeing?
